services:
  - type: web
    name: plinkoo-backend
    env: node
    plan: free
    runtime: node
    branch: main
    region: oregon
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    autoDeploy: true
